### ISSUE TITLE
[Enhancement]Better rcs 

### ISSUE THREAD

**Issue by xleakhvhking** [Nocture-Insight/Dexterion#56]
### 📝 Provide a description of the new feature

title says it

**Comment by xleakhvhking** [comment]
because after you shoot around 5 bullets it goes directly in the ground

**Comment by wqq-z** [comment]
Its mayb a type of a bug

**Comment by Skwrr** [comment]
Never seen it happen to me. Might be an update of the game which modified the recoil pattern and the math in Dexterion might glitch out.

**Comment by LauraSavall** [comment]
> because after you shoot around 5 bullets it goes directly in the ground

Sensitivity in Dexterion is your CS2 mouse sensitivity (to start with....)
