### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by lxwcv** [Nocture-Insight/Dexterion#70]
### 📝 Provide a description of the new feature

How can I find out which enemy has C4?

**Comment by wqq-z** [comment]
Well c4 esp we could make a check to a user holding esp tontraxk them or mske a c4 tracker

**Comment by Skwrr** [comment]
> ### 📝 Provide a description of the new feature
> How can I find out which enemy has C4?
> 
> ### ➕ Additional Information
> _No response_

you can know it if they are holding the c4 and you have "Weapon name" enabled in ESP
